version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  pulsar:
    image: apachepulsar/pulsar:4.0.3
    container_name: pulsar_standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://pulsar:8080/metrics/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone
volumes:
  pulsardata:
      name: pulsardata
  pulsarconf:
    name: pulsarconf