version: '3.8'
services:
  # Servicios de Salud Tech de los Alpes
  saludtechalpes:
    container_name: saludtechalpes
    hostname: saludtechalpes
    image: saludtechalpes/flask
    ports:
      - "5000:5000"
    environment:
      DB_NAME: saludtechalpes
      DB_HOST: saludtechalpes_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      BROKER_HOST: pulsar
    depends_on:
      saludtechalpes_db:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    networks:
      - saludtechalpes_net
      - pulsar
  # Base de datos de Salud Tech de los Alpes
  saludtechalpes_db:
    image: postgres
    volumes:
      - saludtechalpes_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: saludtechalpes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - saludtechalpes_net
  exportacionsta:
    container_name: exportacionsta
    hostname: exportacionsta
    image: exportacionsta/flask
    ports:
      - "5001:5000"
    environment:
      BROKER_HOST: pulsar
    depends_on:
      pulsar:
        condition: service_healthy

    networks:
      - saludtechalpes_net
      - pulsar
  pulsar:
    image: apachepulsar/pulsar:4.0.3
    container_name: pulsar_standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://pulsar:8080/metrics/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone
    networks:
      - pulsar
networks:
  saludtechalpes_net:
  pulsar:
volumes:
  saludtechalpes_data:
  pulsardata:
      name: pulsardata
  pulsarconf:
    name: pulsarconf
