version: '3.8'
services:
  # Servicios de Salud Tech de los Alpes
  saludtechalpes:
    container_name: saludtechalpes
    hostname: saludtechalpes
    image: saludtechalpes/flask
    profiles: [ "saludtechalpes", "monolito" ]
    ports:
      - "5000:5000"
    environment:
      DB_NAME: saludtechalpes
      DB_HOST: saludtechalpes_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      saludtechalpes_db:
        condition: service_healthy
    networks:
      - saludtechalpes_net
  # Base de datos de Salud Tech de los Alpes
  saludtechalpes_db:
    image: postgres
    volumes:
      - saludtechalpes_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: saludtechalpes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - saludtechalpes_net
  exportacionsta:
    container_name: exportacionsta
    hostname: exportacionsta
    image: exportacionsta/flask
    profiles: [ "exportacionsta", "monolito" ]
    ports:
      - "5001:5000"
    depends_on:
      - pulsar

    networks:
      - saludtechalpes_net
      - pulsar
  pulsar:
    image: apachepulsar/pulsar:4.0.3
    container_name: pulsar_standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone
    networks:
      - pulsar
networks:
  saludtechalpes_net:
#  networks:
  pulsar:
#      driver: bridge
volumes:
  saludtechalpes_data:
  pulsardata:
      name: pulsardata
  pulsarconf:
    name: pulsarconf
#  db_comandos_data:
#  db_queries_data:
